// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { TagGroup } from '@heroui/react';
import type { DunetaTagGroupProps, DunetaTagGroupListProps } from './types';

function DunetaTagGroupRoot(props: DunetaTagGroupProps) {
  return <TagGroup {...props} />;
}

function DunetaTagGroupList(props: DunetaTagGroupListProps) {
  return <TagGroup.List {...props} />;
}

export const DunetaTagGroup = Object.assign(DunetaTagGroupRoot, {
  Root: DunetaTagGroupRoot,
  List: DunetaTagGroupList,
});
