// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { TagGroup } from '@heroui/react';

export type DunetaTagGroupProps = ComponentProps<typeof TagGroup>;
export type DunetaTagGroupListProps = ComponentProps<typeof TagGroup.List>;
