// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { SearchField } from '@heroui/react';
import type { DunetaSearchFieldProps, DunetaSearchFieldGroupProps, DunetaSearchFieldInputProps, DunetaSearchFieldSearchIconProps, DunetaSearchFieldClearButtonProps } from './types';

function DunetaSearchFieldRoot(props: DunetaSearchFieldProps) {
  return <SearchField {...props} />;
}

function DunetaSearchFieldGroup(props: DunetaSearchFieldGroupProps) {
  return <SearchField.Group {...props} />;
}

function DunetaSearchFieldInput(props: DunetaSearchFieldInputProps) {
  return <SearchField.Input {...props} />;
}

function DunetaSearchFieldSearchIcon(props: DunetaSearchFieldSearchIconProps) {
  return <SearchField.SearchIcon {...props} />;
}

function DunetaSearchFieldClearButton(props: DunetaSearchFieldClearButtonProps) {
  return <SearchField.ClearButton {...props} />;
}

export const DunetaSearchField = Object.assign(DunetaSearchFieldRoot, {
  Root: DunetaSearchFieldRoot,
  Group: DunetaSearchFieldGroup,
  Input: DunetaSearchFieldInput,
  SearchIcon: DunetaSearchFieldSearchIcon,
  ClearButton: DunetaSearchFieldClearButton,
});
