// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { SearchField } from '@heroui/react';

export type DunetaSearchFieldProps = ComponentProps<typeof SearchField>;
export type DunetaSearchFieldGroupProps = ComponentProps<typeof SearchField.Group>;
export type DunetaSearchFieldInputProps = ComponentProps<typeof SearchField.Input>;
export type DunetaSearchFieldSearchIconProps = ComponentProps<typeof SearchField.SearchIcon>;
export type DunetaSearchFieldClearButtonProps = ComponentProps<typeof SearchField.ClearButton>;
