// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { SwitchGroup } from '@heroui/react';
import type { DunetaSwitchGroupProps } from './types';

function DunetaSwitchGroupRoot(props: DunetaSwitchGroupProps) {
  return <SwitchGroup {...props} />;
}

export const DunetaSwitchGroup = Object.assign(DunetaSwitchGroupRoot, {
  Root: DunetaSwitchGroupRoot,
});
