// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Tabs } from '@heroui/react';
import type { DunetaTabsProps, DunetaTabsListContainerProps, DunetaTabsListProps, DunetaTabsTabProps, DunetaTabsIndicatorProps, DunetaTabsSeparatorProps, DunetaTabsPanelProps } from './types';

function DunetaTabsRoot(props: DunetaTabsProps) {
  return <Tabs {...props} />;
}

function DunetaTabsListContainer(props: DunetaTabsListContainerProps) {
  return <Tabs.ListContainer {...props} />;
}

function DunetaTabsList(props: DunetaTabsListProps) {
  return <Tabs.List {...props} />;
}

function DunetaTabsTab(props: DunetaTabsTabProps) {
  return <Tabs.Tab {...props} />;
}

function DunetaTabsIndicator(props: DunetaTabsIndicatorProps) {
  return <Tabs.Indicator {...props} />;
}

function DunetaTabsSeparator(props: DunetaTabsSeparatorProps) {
  return <Tabs.Separator {...props} />;
}

function DunetaTabsPanel(props: DunetaTabsPanelProps) {
  return <Tabs.Panel {...props} />;
}

export const DunetaTabs = Object.assign(DunetaTabsRoot, {
  Root: DunetaTabsRoot,
  ListContainer: DunetaTabsListContainer,
  List: DunetaTabsList,
  Tab: DunetaTabsTab,
  Indicator: DunetaTabsIndicator,
  Separator: DunetaTabsSeparator,
  Panel: DunetaTabsPanel,
});
