// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Tabs } from '@heroui/react';

export type DunetaTabsProps = ComponentProps<typeof Tabs>;
export type DunetaTabsListContainerProps = ComponentProps<typeof Tabs.ListContainer>;
export type DunetaTabsListProps = ComponentProps<typeof Tabs.List>;
export type DunetaTabsTabProps = ComponentProps<typeof Tabs.Tab>;
export type DunetaTabsIndicatorProps = ComponentProps<typeof Tabs.Indicator>;
export type DunetaTabsSeparatorProps = ComponentProps<typeof Tabs.Separator>;
export type DunetaTabsPanelProps = ComponentProps<typeof Tabs.Panel>;
