// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Dropdown } from '@heroui/react';
import type { DunetaDropdownProps, DunetaDropdownTriggerProps, DunetaDropdownPopoverProps, DunetaDropdownMenuProps, DunetaDropdownSectionProps, DunetaDropdownItemProps, DunetaDropdownItemIndicatorProps, DunetaDropdownSubmenuIndicatorProps, DunetaDropdownSubmenuTriggerProps } from './types';

function DunetaDropdownRoot(props: DunetaDropdownProps) {
  return <Dropdown {...props} />;
}

function DunetaDropdownTrigger(props: DunetaDropdownTriggerProps) {
  return <Dropdown.Trigger {...props} />;
}

function DunetaDropdownPopover(props: DunetaDropdownPopoverProps) {
  return <Dropdown.Popover {...props} />;
}

function DunetaDropdownMenu(props: DunetaDropdownMenuProps) {
  return <Dropdown.Menu {...props} />;
}

function DunetaDropdownSection(props: DunetaDropdownSectionProps) {
  return <Dropdown.Section {...props} />;
}

function DunetaDropdownItem(props: DunetaDropdownItemProps) {
  return <Dropdown.Item {...props} />;
}

function DunetaDropdownItemIndicator(props: DunetaDropdownItemIndicatorProps) {
  return <Dropdown.ItemIndicator {...props} />;
}

function DunetaDropdownSubmenuIndicator(props: DunetaDropdownSubmenuIndicatorProps) {
  return <Dropdown.SubmenuIndicator {...props} />;
}

function DunetaDropdownSubmenuTrigger(props: DunetaDropdownSubmenuTriggerProps) {
  return <Dropdown.SubmenuTrigger {...props} />;
}

export const DunetaDropdown = Object.assign(DunetaDropdownRoot, {
  Root: DunetaDropdownRoot,
  Trigger: DunetaDropdownTrigger,
  Popover: DunetaDropdownPopover,
  Menu: DunetaDropdownMenu,
  Section: DunetaDropdownSection,
  Item: DunetaDropdownItem,
  ItemIndicator: DunetaDropdownItemIndicator,
  SubmenuIndicator: DunetaDropdownSubmenuIndicator,
  SubmenuTrigger: DunetaDropdownSubmenuTrigger,
});
