// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Dropdown } from '@heroui/react';

export type DunetaDropdownProps = ComponentProps<typeof Dropdown>;
export type DunetaDropdownTriggerProps = ComponentProps<typeof Dropdown.Trigger>;
export type DunetaDropdownPopoverProps = ComponentProps<typeof Dropdown.Popover>;
export type DunetaDropdownMenuProps = ComponentProps<typeof Dropdown.Menu>;
export type DunetaDropdownSectionProps = ComponentProps<typeof Dropdown.Section>;
export type DunetaDropdownItemProps = ComponentProps<typeof Dropdown.Item>;
export type DunetaDropdownItemIndicatorProps = ComponentProps<typeof Dropdown.ItemIndicator>;
export type DunetaDropdownSubmenuIndicatorProps = ComponentProps<typeof Dropdown.SubmenuIndicator>;
export type DunetaDropdownSubmenuTriggerProps = ComponentProps<typeof Dropdown.SubmenuTrigger>;
