// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { RadioGroup } from '@heroui/react';
import type { DunetaRadioGroupProps } from './types';

function DunetaRadioGroupRoot(props: DunetaRadioGroupProps) {
  return <RadioGroup {...props} />;
}

export const DunetaRadioGroup = Object.assign(DunetaRadioGroupRoot, {
  Root: DunetaRadioGroupRoot,
});
