// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { RangeCalendar } from '@heroui/react';
import type { DunetaRangeCalendarProps, DunetaRangeCalendarHeaderProps } from './types';

function DunetaRangeCalendarRoot(props: DunetaRangeCalendarProps) {
  return <RangeCalendar {...props} />;
}

function DunetaRangeCalendarHeader(props: DunetaRangeCalendarHeaderProps) {
  return <RangeCalendar.Header {...props} />;
}

export const DunetaRangeCalendar = Object.assign(DunetaRangeCalendarRoot, {
  Root: DunetaRangeCalendarRoot,
  Header: DunetaRangeCalendarHeader,
});
