// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { RangeCalendar } from '@heroui/react';

export type DunetaRangeCalendarProps = ComponentProps<typeof RangeCalendar>;
export type DunetaRangeCalendarHeaderProps = ComponentProps<typeof RangeCalendar.Header>;
