// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Switch } from '@heroui/react';
import type { DunetaSwitchProps } from './types';

function DunetaSwitchRoot(props: DunetaSwitchProps) {
  return <Switch {...props} />;
}

export const DunetaSwitch = Object.assign(DunetaSwitchRoot, {
  Root: DunetaSwitchRoot,
});
