// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Switch } from '@heroui/react';

export type DunetaSwitchProps = ComponentProps<typeof Switch>;
