// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Popover } from '@heroui/react';
import type { DunetaPopoverProps, DunetaPopoverTriggerProps, DunetaPopoverDialogProps, DunetaPopoverArrowProps, DunetaPopoverContentProps, DunetaPopoverHeadingProps } from './types';

function DunetaPopoverRoot(props: DunetaPopoverProps) {
  return <Popover {...props} />;
}

function DunetaPopoverTrigger(props: DunetaPopoverTriggerProps) {
  return <Popover.Trigger {...props} />;
}

function DunetaPopoverDialog(props: DunetaPopoverDialogProps) {
  return <Popover.Dialog {...props} />;
}

function DunetaPopoverArrow(props: DunetaPopoverArrowProps) {
  return <Popover.Arrow {...props} />;
}

function DunetaPopoverContent(props: DunetaPopoverContentProps) {
  return <Popover.Content {...props} />;
}

function DunetaPopoverHeading(props: DunetaPopoverHeadingProps) {
  return <Popover.Heading {...props} />;
}

export const DunetaPopover = Object.assign(DunetaPopoverRoot, {
  Root: DunetaPopoverRoot,
  Trigger: DunetaPopoverTrigger,
  Dialog: DunetaPopoverDialog,
  Arrow: DunetaPopoverArrow,
  Content: DunetaPopoverContent,
  Heading: DunetaPopoverHeading,
});
