// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Popover } from '@heroui/react';

export type DunetaPopoverProps = ComponentProps<typeof Popover>;
export type DunetaPopoverTriggerProps = ComponentProps<typeof Popover.Trigger>;
export type DunetaPopoverDialogProps = ComponentProps<typeof Popover.Dialog>;
export type DunetaPopoverArrowProps = ComponentProps<typeof Popover.Arrow>;
export type DunetaPopoverContentProps = ComponentProps<typeof Popover.Content>;
export type DunetaPopoverHeadingProps = ComponentProps<typeof Popover.Heading>;
