// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { EmptyState } from '@heroui/react';
import type { DunetaEmptyStateProps } from './types';

function DunetaEmptyStateRoot(props: DunetaEmptyStateProps) {
  return <EmptyState {...props} />;
}

export const DunetaEmptyState = Object.assign(DunetaEmptyStateRoot, {
  Root: DunetaEmptyStateRoot,
});
