// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { EmptyState } from '@heroui/react';

export type DunetaEmptyStateProps = ComponentProps<typeof EmptyState>;
