// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Link } from '@heroui/react';
import type { DunetaHrefLinkProps, DunetaHrefLinkIconProps } from './types';

function DunetaHrefLinkRoot(props: DunetaHrefLinkProps) {
  return <Link {...props} />;
}

function DunetaHrefLinkIcon(props: DunetaHrefLinkIconProps) {
  return <Link.Icon {...props} />;
}

export const DunetaHrefLink = Object.assign(DunetaHrefLinkRoot, {
  Root: DunetaHrefLinkRoot,
  Icon: DunetaHrefLinkIcon,
});
