// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Link } from '@heroui/react';

export type DunetaHrefLinkProps = ComponentProps<typeof Link>;
export type DunetaHrefLinkIconProps = ComponentProps<typeof Link.Icon>;
