// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Card } from '@heroui/react';
import type { DunetaCardProps, DunetaCardHeaderProps, DunetaCardTitleProps, DunetaCardDescriptionProps, DunetaCardContentProps, DunetaCardFooterProps } from './types';

function DunetaCardRoot(props: DunetaCardProps) {
  return <Card {...props} />;
}

function DunetaCardHeader(props: DunetaCardHeaderProps) {
  return <Card.Header {...props} />;
}

function DunetaCardTitle(props: DunetaCardTitleProps) {
  return <Card.Title {...props} />;
}

function DunetaCardDescription(props: DunetaCardDescriptionProps) {
  return <Card.Description {...props} />;
}

function DunetaCardContent(props: DunetaCardContentProps) {
  return <Card.Content {...props} />;
}

function DunetaCardFooter(props: DunetaCardFooterProps) {
  return <Card.Footer {...props} />;
}

export const DunetaCard = Object.assign(DunetaCardRoot, {
  Root: DunetaCardRoot,
  Header: DunetaCardHeader,
  Title: DunetaCardTitle,
  Description: DunetaCardDescription,
  Content: DunetaCardContent,
  Footer: DunetaCardFooter,
});
