// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Card } from '@heroui/react';

export type DunetaCardProps = ComponentProps<typeof Card>;
export type DunetaCardHeaderProps = ComponentProps<typeof Card.Header>;
export type DunetaCardTitleProps = ComponentProps<typeof Card.Title>;
export type DunetaCardDescriptionProps = ComponentProps<typeof Card.Description>;
export type DunetaCardContentProps = ComponentProps<typeof Card.Content>;
export type DunetaCardFooterProps = ComponentProps<typeof Card.Footer>;
