// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Toast } from '@heroui/react';
import type { DunetaToastProps, DunetaToastProviderProps } from './types';

function DunetaToastRoot(props: DunetaToastProps) {
  return <Toast {...props} />;
}

function DunetaToastProvider(props: DunetaToastProviderProps) {
  return <Toast.Provider {...props} />;
}

export const DunetaToast = Object.assign(DunetaToastRoot, {
  Root: DunetaToastRoot,
  Provider: DunetaToastProvider,
});
