// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Toast } from '@heroui/react';

export type DunetaToastProps = ComponentProps<typeof Toast>;
export type DunetaToastProviderProps = ComponentProps<typeof Toast.Provider>;
