// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Disclosure } from '@heroui/react';
import type { DunetaDisclosureProps, DunetaDisclosureHeadingProps, DunetaDisclosureTriggerProps, DunetaDisclosureContentProps, DunetaDisclosureBodyProps, DunetaDisclosureIndicatorProps } from './types';

function DunetaDisclosureRoot(props: DunetaDisclosureProps) {
  return <Disclosure {...props} />;
}

function DunetaDisclosureHeading(props: DunetaDisclosureHeadingProps) {
  return <Disclosure.Heading {...props} />;
}

function DunetaDisclosureTrigger(props: DunetaDisclosureTriggerProps) {
  return <Disclosure.Trigger {...props} />;
}

function DunetaDisclosureContent(props: DunetaDisclosureContentProps) {
  return <Disclosure.Content {...props} />;
}

function DunetaDisclosureBody(props: DunetaDisclosureBodyProps) {
  return <Disclosure.Body {...props} />;
}

function DunetaDisclosureIndicator(props: DunetaDisclosureIndicatorProps) {
  return <Disclosure.Indicator {...props} />;
}

export const DunetaDisclosure = Object.assign(DunetaDisclosureRoot, {
  Root: DunetaDisclosureRoot,
  Heading: DunetaDisclosureHeading,
  Trigger: DunetaDisclosureTrigger,
  Content: DunetaDisclosureContent,
  Body: DunetaDisclosureBody,
  Indicator: DunetaDisclosureIndicator,
});
