// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Disclosure } from '@heroui/react';

export type DunetaDisclosureProps = ComponentProps<typeof Disclosure>;
export type DunetaDisclosureHeadingProps = ComponentProps<typeof Disclosure.Heading>;
export type DunetaDisclosureTriggerProps = ComponentProps<typeof Disclosure.Trigger>;
export type DunetaDisclosureContentProps = ComponentProps<typeof Disclosure.Content>;
export type DunetaDisclosureBodyProps = ComponentProps<typeof Disclosure.Body>;
export type DunetaDisclosureIndicatorProps = ComponentProps<typeof Disclosure.Indicator>;
