// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { InputGroup } from '@heroui/react';
import type { DunetaInputGroupProps, DunetaInputGroupInputProps, DunetaInputGroupTextAreaProps, DunetaInputGroupPrefixProps, DunetaInputGroupSuffixProps } from './types';

function DunetaInputGroupRoot(props: DunetaInputGroupProps) {
  return <InputGroup {...props} />;
}

function DunetaInputGroupInput(props: DunetaInputGroupInputProps) {
  return <InputGroup.Input {...props} />;
}

function DunetaInputGroupTextArea(props: DunetaInputGroupTextAreaProps) {
  return <InputGroup.TextArea {...props} />;
}

function DunetaInputGroupPrefix(props: DunetaInputGroupPrefixProps) {
  return <InputGroup.Prefix {...props} />;
}

function DunetaInputGroupSuffix(props: DunetaInputGroupSuffixProps) {
  return <InputGroup.Suffix {...props} />;
}

export const DunetaInputGroup = Object.assign(DunetaInputGroupRoot, {
  Root: DunetaInputGroupRoot,
  Input: DunetaInputGroupInput,
  TextArea: DunetaInputGroupTextArea,
  Prefix: DunetaInputGroupPrefix,
  Suffix: DunetaInputGroupSuffix,
});
