// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { InputGroup } from '@heroui/react';

export type DunetaInputGroupProps = ComponentProps<typeof InputGroup>;
export type DunetaInputGroupInputProps = ComponentProps<typeof InputGroup.Input>;
export type DunetaInputGroupTextAreaProps = ComponentProps<typeof InputGroup.TextArea>;
export type DunetaInputGroupPrefixProps = ComponentProps<typeof InputGroup.Prefix>;
export type DunetaInputGroupSuffixProps = ComponentProps<typeof InputGroup.Suffix>;
