// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { CloseButton } from '@heroui/react';
import type { DunetaCloseButtonProps } from './types';

function DunetaCloseButtonRoot(props: DunetaCloseButtonProps) {
  return <CloseButton {...props} />;
}

export const DunetaCloseButton = Object.assign(DunetaCloseButtonRoot, {
  Root: DunetaCloseButtonRoot,
});
