// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { CloseButton } from '@heroui/react';

export type DunetaCloseButtonProps = ComponentProps<typeof CloseButton>;
