// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ColorField } from '@heroui/react';
import type { DunetaColorFieldProps, DunetaColorFieldGroupProps, DunetaColorFieldInputProps, DunetaColorFieldPrefixProps, DunetaColorFieldSuffixProps } from './types';

function DunetaColorFieldRoot(props: DunetaColorFieldProps) {
  return <ColorField {...props} />;
}

function DunetaColorFieldGroup(props: DunetaColorFieldGroupProps) {
  return <ColorField.Group {...props} />;
}

function DunetaColorFieldInput(props: DunetaColorFieldInputProps) {
  return <ColorField.Input {...props} />;
}

function DunetaColorFieldPrefix(props: DunetaColorFieldPrefixProps) {
  return <ColorField.Prefix {...props} />;
}

function DunetaColorFieldSuffix(props: DunetaColorFieldSuffixProps) {
  return <ColorField.Suffix {...props} />;
}

export const DunetaColorField = Object.assign(DunetaColorFieldRoot, {
  Root: DunetaColorFieldRoot,
  Group: DunetaColorFieldGroup,
  Input: DunetaColorFieldInput,
  Prefix: DunetaColorFieldPrefix,
  Suffix: DunetaColorFieldSuffix,
});
