// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { ColorField } from '@heroui/react';

export type DunetaColorFieldProps = ComponentProps<typeof ColorField>;
export type DunetaColorFieldGroupProps = ComponentProps<typeof ColorField.Group>;
export type DunetaColorFieldInputProps = ComponentProps<typeof ColorField.Input>;
export type DunetaColorFieldPrefixProps = ComponentProps<typeof ColorField.Prefix>;
export type DunetaColorFieldSuffixProps = ComponentProps<typeof ColorField.Suffix>;
