// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ColorSwatchPicker } from '@heroui/react';
import type { DunetaColorSwatchPickerProps, DunetaColorSwatchPickerItemProps, DunetaColorSwatchPickerSwatchProps, DunetaColorSwatchPickerIndicatorProps } from './types';

function DunetaColorSwatchPickerRoot(props: DunetaColorSwatchPickerProps) {
  return <ColorSwatchPicker {...props} />;
}

function DunetaColorSwatchPickerItem(props: DunetaColorSwatchPickerItemProps) {
  return <ColorSwatchPicker.Item {...props} />;
}

function DunetaColorSwatchPickerSwatch(props: DunetaColorSwatchPickerSwatchProps) {
  return <ColorSwatchPicker.Swatch {...props} />;
}

function DunetaColorSwatchPickerIndicator(props: DunetaColorSwatchPickerIndicatorProps) {
  return <ColorSwatchPicker.Indicator {...props} />;
}

export const DunetaColorSwatchPicker = Object.assign(DunetaColorSwatchPickerRoot, {
  Root: DunetaColorSwatchPickerRoot,
  Item: DunetaColorSwatchPickerItem,
  Swatch: DunetaColorSwatchPickerSwatch,
  Indicator: DunetaColorSwatchPickerIndicator,
});
