// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { ColorSwatchPicker } from '@heroui/react';

export type DunetaColorSwatchPickerProps = ComponentProps<typeof ColorSwatchPicker>;
export type DunetaColorSwatchPickerItemProps = ComponentProps<typeof ColorSwatchPicker.Item>;
export type DunetaColorSwatchPickerSwatchProps = ComponentProps<typeof ColorSwatchPicker.Swatch>;
export type DunetaColorSwatchPickerIndicatorProps = ComponentProps<typeof ColorSwatchPicker.Indicator>;
