// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Spinner } from '@heroui/react';
import type { DunetaSpinnerProps } from './types';

function DunetaSpinnerRoot(props: DunetaSpinnerProps) {
  return <Spinner {...props} />;
}

export const DunetaSpinner = Object.assign(DunetaSpinnerRoot, {
  Root: DunetaSpinnerRoot,
});
