// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Spinner } from '@heroui/react';

export type DunetaSpinnerProps = ComponentProps<typeof Spinner>;
