// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { TextField } from '@heroui/react';
import type { DunetaTextFieldProps } from './types';

function DunetaTextFieldRoot(props: DunetaTextFieldProps) {
  return <TextField {...props} />;
}

export const DunetaTextField = Object.assign(DunetaTextFieldRoot, {
  Root: DunetaTextFieldRoot,
});
