// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { TextField } from '@heroui/react';

export type DunetaTextFieldProps = ComponentProps<typeof TextField>;
