// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Calendar } from '@heroui/react';
import type { DunetaCalendarProps } from './types';

function DunetaCalendarRoot(props: DunetaCalendarProps) {
  return <Calendar {...props} />;
}

export const DunetaCalendar = Object.assign(DunetaCalendarRoot, {
  Root: DunetaCalendarRoot,
});
