// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Calendar } from '@heroui/react';

export type DunetaCalendarProps = ComponentProps<typeof Calendar>;
