// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ColorPicker } from '@heroui/react';
import type { DunetaColorPickerProps, DunetaColorPickerTriggerProps, DunetaColorPickerPopoverProps } from './types';

function DunetaColorPickerRoot(props: DunetaColorPickerProps) {
  return <ColorPicker {...props} />;
}

function DunetaColorPickerTrigger(props: DunetaColorPickerTriggerProps) {
  return <ColorPicker.Trigger {...props} />;
}

function DunetaColorPickerPopover(props: DunetaColorPickerPopoverProps) {
  return <ColorPicker.Popover {...props} />;
}

export const DunetaColorPicker = Object.assign(DunetaColorPickerRoot, {
  Root: DunetaColorPickerRoot,
  Trigger: DunetaColorPickerTrigger,
  Popover: DunetaColorPickerPopover,
});
