// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { ColorPicker } from '@heroui/react';

export type DunetaColorPickerProps = ComponentProps<typeof ColorPicker>;
export type DunetaColorPickerTriggerProps = ComponentProps<typeof ColorPicker.Trigger>;
export type DunetaColorPickerPopoverProps = ComponentProps<typeof ColorPicker.Popover>;
