// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ProgressBar } from '@heroui/react';
import type { DunetaProgressBarProps } from './types';

function DunetaProgressBarRoot(props: DunetaProgressBarProps) {
  return <ProgressBar {...props} />;
}

export const DunetaProgressBar = Object.assign(DunetaProgressBarRoot, {
  Root: DunetaProgressBarRoot,
});
