// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Badge } from '@heroui/react';
import type { DunetaBadgeProps, DunetaBadgeAnchorProps, DunetaBadgeLabelProps } from './types';

function DunetaBadgeRoot(props: DunetaBadgeProps) {
  return <Badge {...props} />;
}

function DunetaBadgeAnchor(props: DunetaBadgeAnchorProps) {
  return <Badge.Anchor {...props} />;
}

function DunetaBadgeLabel(props: DunetaBadgeLabelProps) {
  return <Badge.Label {...props} />;
}

export const DunetaBadge = Object.assign(DunetaBadgeRoot, {
  Root: DunetaBadgeRoot,
  Anchor: DunetaBadgeAnchor,
  Label: DunetaBadgeLabel,
});
