// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Badge } from '@heroui/react';

export type DunetaBadgeProps = ComponentProps<typeof Badge>;
export type DunetaBadgeAnchorProps = ComponentProps<typeof Badge.Anchor>;
export type DunetaBadgeLabelProps = ComponentProps<typeof Badge.Label>;
