// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Description } from '@heroui/react';
import type { DunetaDescriptionProps } from './types';

function DunetaDescriptionRoot(props: DunetaDescriptionProps) {
  return <Description {...props} />;
}

export const DunetaDescription = Object.assign(DunetaDescriptionRoot, {
  Root: DunetaDescriptionRoot,
});
