// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Fieldset } from '@heroui/react';
import type { DunetaFieldsetProps, DunetaFieldsetLegendProps, DunetaFieldsetGroupProps, DunetaFieldsetActionsProps } from './types';

function DunetaFieldsetRoot(props: DunetaFieldsetProps) {
  return <Fieldset {...props} />;
}

function DunetaFieldsetLegend(props: DunetaFieldsetLegendProps) {
  return <Fieldset.Legend {...props} />;
}

function DunetaFieldsetGroup(props: DunetaFieldsetGroupProps) {
  return <Fieldset.Group {...props} />;
}

function DunetaFieldsetActions(props: DunetaFieldsetActionsProps) {
  return <Fieldset.Actions {...props} />;
}

export const DunetaFieldset = Object.assign(DunetaFieldsetRoot, {
  Root: DunetaFieldsetRoot,
  Legend: DunetaFieldsetLegend,
  Group: DunetaFieldsetGroup,
  Actions: DunetaFieldsetActions,
});
