// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Fieldset } from '@heroui/react';

export type DunetaFieldsetProps = ComponentProps<typeof Fieldset>;
export type DunetaFieldsetLegendProps = ComponentProps<typeof Fieldset.Legend>;
export type DunetaFieldsetGroupProps = ComponentProps<typeof Fieldset.Group>;
export type DunetaFieldsetActionsProps = ComponentProps<typeof Fieldset.Actions>;
