// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ProgressCircle } from '@heroui/react';
import type { DunetaProgressCircleProps } from './types';

function DunetaProgressCircleRoot(props: DunetaProgressCircleProps) {
  return <ProgressCircle {...props} />;
}

export const DunetaProgressCircle = Object.assign(DunetaProgressCircleRoot, {
  Root: DunetaProgressCircleRoot,
});
