// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { ProgressCircle } from '@heroui/react';

export type DunetaProgressCircleProps = ComponentProps<typeof ProgressCircle>;
