// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Modal } from '@heroui/react';
import type { DunetaModalProps, DunetaModalTriggerProps, DunetaModalBackdropProps, DunetaModalContainerProps, DunetaModalDialogProps, DunetaModalHeaderProps, DunetaModalIconProps, DunetaModalHeadingProps, DunetaModalBodyProps, DunetaModalFooterProps, DunetaModalCloseTriggerProps } from './types';

function DunetaModalRoot(props: DunetaModalProps) {
  return <Modal {...props} />;
}

function DunetaModalTrigger(props: DunetaModalTriggerProps) {
  return <Modal.Trigger {...props} />;
}

function DunetaModalBackdrop(props: DunetaModalBackdropProps) {
  return <Modal.Backdrop {...props} />;
}

function DunetaModalContainer(props: DunetaModalContainerProps) {
  return <Modal.Container {...props} />;
}

function DunetaModalDialog(props: DunetaModalDialogProps) {
  return <Modal.Dialog {...props} />;
}

function DunetaModalHeader(props: DunetaModalHeaderProps) {
  return <Modal.Header {...props} />;
}

function DunetaModalIcon(props: DunetaModalIconProps) {
  return <Modal.Icon {...props} />;
}

function DunetaModalHeading(props: DunetaModalHeadingProps) {
  return <Modal.Heading {...props} />;
}

function DunetaModalBody(props: DunetaModalBodyProps) {
  return <Modal.Body {...props} />;
}

function DunetaModalFooter(props: DunetaModalFooterProps) {
  return <Modal.Footer {...props} />;
}

function DunetaModalCloseTrigger(props: DunetaModalCloseTriggerProps) {
  return <Modal.CloseTrigger {...props} />;
}

export const DunetaModal = Object.assign(DunetaModalRoot, {
  Root: DunetaModalRoot,
  Trigger: DunetaModalTrigger,
  Backdrop: DunetaModalBackdrop,
  Container: DunetaModalContainer,
  Dialog: DunetaModalDialog,
  Header: DunetaModalHeader,
  Icon: DunetaModalIcon,
  Heading: DunetaModalHeading,
  Body: DunetaModalBody,
  Footer: DunetaModalFooter,
  CloseTrigger: DunetaModalCloseTrigger,
});
