// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Modal } from '@heroui/react';

export type DunetaModalProps = ComponentProps<typeof Modal>;
export type DunetaModalTriggerProps = ComponentProps<typeof Modal.Trigger>;
export type DunetaModalBackdropProps = ComponentProps<typeof Modal.Backdrop>;
export type DunetaModalContainerProps = ComponentProps<typeof Modal.Container>;
export type DunetaModalDialogProps = ComponentProps<typeof Modal.Dialog>;
export type DunetaModalHeaderProps = ComponentProps<typeof Modal.Header>;
export type DunetaModalIconProps = ComponentProps<typeof Modal.Icon>;
export type DunetaModalHeadingProps = ComponentProps<typeof Modal.Heading>;
export type DunetaModalBodyProps = ComponentProps<typeof Modal.Body>;
export type DunetaModalFooterProps = ComponentProps<typeof Modal.Footer>;
export type DunetaModalCloseTriggerProps = ComponentProps<typeof Modal.CloseTrigger>;
