// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Tooltip } from '@heroui/react';
import type { DunetaTooltipProps, DunetaTooltipTriggerProps, DunetaTooltipContentProps, DunetaTooltipArrowProps } from './types';

function DunetaTooltipRoot(props: DunetaTooltipProps) {
  return <Tooltip {...props} />;
}

function DunetaTooltipTrigger(props: DunetaTooltipTriggerProps) {
  return <Tooltip.Trigger {...props} />;
}

function DunetaTooltipContent(props: DunetaTooltipContentProps) {
  return <Tooltip.Content {...props} />;
}

function DunetaTooltipArrow(props: DunetaTooltipArrowProps) {
  return <Tooltip.Arrow {...props} />;
}

export const DunetaTooltip = Object.assign(DunetaTooltipRoot, {
  Root: DunetaTooltipRoot,
  Trigger: DunetaTooltipTrigger,
  Content: DunetaTooltipContent,
  Arrow: DunetaTooltipArrow,
});
