// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Tooltip } from '@heroui/react';

export type DunetaTooltipProps = ComponentProps<typeof Tooltip>;
export type DunetaTooltipTriggerProps = ComponentProps<typeof Tooltip.Trigger>;
export type DunetaTooltipContentProps = ComponentProps<typeof Tooltip.Content>;
export type DunetaTooltipArrowProps = ComponentProps<typeof Tooltip.Arrow>;
