// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Pagination } from '@heroui/react';
import { cn } from '../../../core/cn.js';
import type {
  DunetaPaginationContentProps,
  DunetaPaginationEllipsisProps,
  DunetaPaginationItemProps,
  DunetaPaginationLinkProps,
  DunetaPaginationNextIconProps,
  DunetaPaginationNextProps,
  DunetaPaginationPreviousIconProps,
  DunetaPaginationPreviousProps,
  DunetaPaginationProps,
  DunetaPaginationSummaryProps,
} from './types';

function DunetaPaginationRoot(props: DunetaPaginationProps) {
  return <Pagination {...props} />;
}

function DunetaPaginationSummary(props: DunetaPaginationSummaryProps) {
  return <Pagination.Summary {...props} />;
}

function DunetaPaginationContent(props: DunetaPaginationContentProps) {
  return <Pagination.Content {...props} />;
}

function DunetaPaginationItem(props: DunetaPaginationItemProps) {
  return <Pagination.Item {...props} />;
}

const ACTIVE_LINK_CLASS =
  'data-[active=true]:[--pagination-link-bg:var(--accent)] data-[active=true]:[--pagination-link-fg:var(--accent-foreground)] data-[active=true]:[--pagination-link-bg-hover:var(--accent-hover)] data-[active=true]:[--pagination-link-bg-pressed:var(--accent-hover)]';

function DunetaPaginationLink({
  className,
  isActive,
  ...props
}: DunetaPaginationLinkProps) {
  return (
    <Pagination.Link
      className={cn(isActive && ACTIVE_LINK_CLASS, className)}
      isActive={isActive}
      {...props}
    />
  );
}

function DunetaPaginationPrevious(props: DunetaPaginationPreviousProps) {
  return <Pagination.Previous {...props} />;
}

function DunetaPaginationPreviousIcon(props: DunetaPaginationPreviousIconProps) {
  return <Pagination.PreviousIcon {...props} />;
}

function DunetaPaginationNext(props: DunetaPaginationNextProps) {
  return <Pagination.Next {...props} />;
}

function DunetaPaginationNextIcon(props: DunetaPaginationNextIconProps) {
  return <Pagination.NextIcon {...props} />;
}

function DunetaPaginationEllipsis(props: DunetaPaginationEllipsisProps) {
  return <Pagination.Ellipsis {...props} />;
}

export const DunetaPagination = Object.assign(DunetaPaginationRoot, {
  Root: DunetaPaginationRoot,
  Summary: DunetaPaginationSummary,
  Content: DunetaPaginationContent,
  Item: DunetaPaginationItem,
  Link: DunetaPaginationLink,
  Previous: DunetaPaginationPrevious,
  PreviousIcon: DunetaPaginationPreviousIcon,
  Next: DunetaPaginationNext,
  NextIcon: DunetaPaginationNextIcon,
  Ellipsis: DunetaPaginationEllipsis,
});
