// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Pagination } from '@heroui/react';

export type DunetaPaginationProps = ComponentProps<typeof Pagination>;
export type DunetaPaginationSummaryProps = ComponentProps<typeof Pagination.Summary>;
export type DunetaPaginationContentProps = ComponentProps<typeof Pagination.Content>;
export type DunetaPaginationItemProps = ComponentProps<typeof Pagination.Item>;
export type DunetaPaginationLinkProps = ComponentProps<typeof Pagination.Link>;
export type DunetaPaginationPreviousProps = ComponentProps<typeof Pagination.Previous>;
export type DunetaPaginationPreviousIconProps = ComponentProps<
  typeof Pagination.PreviousIcon
>;
export type DunetaPaginationNextProps = ComponentProps<typeof Pagination.Next>;
export type DunetaPaginationNextIconProps = ComponentProps<typeof Pagination.NextIcon>;
export type DunetaPaginationEllipsisProps = ComponentProps<typeof Pagination.Ellipsis>;
