// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { DateRangePicker } from '@heroui/react';
import type { DunetaDateRangePickerProps } from './types';

function DunetaDateRangePickerRoot(props: DunetaDateRangePickerProps) {
  return <DateRangePicker {...props} />;
}

export const DunetaDateRangePicker = Object.assign(DunetaDateRangePickerRoot, {
  Root: DunetaDateRangePickerRoot,
});
