// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { DateRangePicker } from '@heroui/react';

export type DunetaDateRangePickerProps = ComponentProps<typeof DateRangePicker>;
