// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Kbd } from '@heroui/react';
import type { DunetaKbdProps, DunetaKbdAbbrProps, DunetaKbdContentProps } from './types';

function DunetaKbdRoot(props: DunetaKbdProps) {
  return <Kbd {...props} />;
}

function DunetaKbdAbbr(props: DunetaKbdAbbrProps) {
  return <Kbd.Abbr {...props} />;
}

function DunetaKbdContent(props: DunetaKbdContentProps) {
  return <Kbd.Content {...props} />;
}

export const DunetaKbd = Object.assign(DunetaKbdRoot, {
  Root: DunetaKbdRoot,
  Abbr: DunetaKbdAbbr,
  Content: DunetaKbdContent,
});
