// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Kbd } from '@heroui/react';

export type DunetaKbdProps = ComponentProps<typeof Kbd>;
export type DunetaKbdAbbrProps = ComponentProps<typeof Kbd.Abbr>;
export type DunetaKbdContentProps = ComponentProps<typeof Kbd.Content>;
