// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Chip } from '@heroui/react';
import type { DunetaChipProps, DunetaChipLabelProps } from './types';

function DunetaChipRoot(props: DunetaChipProps) {
  return <Chip {...props} />;
}

function DunetaChipLabel(props: DunetaChipLabelProps) {
  return <Chip.Label {...props} />;
}

export const DunetaChip = Object.assign(DunetaChipRoot, {
  Root: DunetaChipRoot,
  Label: DunetaChipLabel,
});
