// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Chip } from '@heroui/react';

export type DunetaChipProps = ComponentProps<typeof Chip>;
export type DunetaChipLabelProps = ComponentProps<typeof Chip.Label>;
