// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Typography } from '@heroui/react';
import type { DunetaTypographyProps, DunetaTypographyCodeProps, DunetaTypographyHeadingProps, DunetaTypographyParagraphProps, DunetaTypographyProseProps } from './types';

function DunetaTypographyRoot(props: DunetaTypographyProps) {
  return <Typography {...props} />;
}

function DunetaTypographyCode(props: DunetaTypographyCodeProps) {
  return <Typography.Code {...props} />;
}

function DunetaTypographyHeading(props: DunetaTypographyHeadingProps) {
  return <Typography.Heading {...props} />;
}

function DunetaTypographyParagraph(props: DunetaTypographyParagraphProps) {
  return <Typography.Paragraph {...props} />;
}

function DunetaTypographyProse(props: DunetaTypographyProseProps) {
  return <Typography.Prose {...props} />;
}

export const DunetaTypography = Object.assign(DunetaTypographyRoot, {
  Root: DunetaTypographyRoot,
  Code: DunetaTypographyCode,
  Heading: DunetaTypographyHeading,
  Paragraph: DunetaTypographyParagraph,
  Prose: DunetaTypographyProse,
});
