// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Typography } from '@heroui/react';

export type DunetaTypographyProps = ComponentProps<typeof Typography>;
export type DunetaTypographyCodeProps = ComponentProps<typeof Typography.Code>;
export type DunetaTypographyHeadingProps = ComponentProps<typeof Typography.Heading>;
export type DunetaTypographyParagraphProps = ComponentProps<typeof Typography.Paragraph>;
export type DunetaTypographyProseProps = ComponentProps<typeof Typography.Prose>;
