// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Label } from '@heroui/react';
import type { DunetaLabelProps } from './types';

function DunetaLabelRoot(props: DunetaLabelProps) {
  return <Label {...props} />;
}

export const DunetaLabel = Object.assign(DunetaLabelRoot, {
  Root: DunetaLabelRoot,
});
