// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Label } from '@heroui/react';

export type DunetaLabelProps = ComponentProps<typeof Label>;
