// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { DateField } from '@heroui/react';
import type { DunetaDateFieldProps, DunetaDateFieldGroupProps, DunetaDateFieldInputProps, DunetaDateFieldInputContainerProps, DunetaDateFieldSegmentProps, DunetaDateFieldPrefixProps, DunetaDateFieldSuffixProps } from './types';

function DunetaDateFieldRoot(props: DunetaDateFieldProps) {
  return <DateField {...props} />;
}

function DunetaDateFieldGroup(props: DunetaDateFieldGroupProps) {
  return <DateField.Group {...props} />;
}

function DunetaDateFieldInput(props: DunetaDateFieldInputProps) {
  return <DateField.Input {...props} />;
}

function DunetaDateFieldInputContainer(props: DunetaDateFieldInputContainerProps) {
  return <DateField.InputContainer {...props} />;
}

function DunetaDateFieldSegment(props: DunetaDateFieldSegmentProps) {
  return <DateField.Segment {...props} />;
}

function DunetaDateFieldPrefix(props: DunetaDateFieldPrefixProps) {
  return <DateField.Prefix {...props} />;
}

function DunetaDateFieldSuffix(props: DunetaDateFieldSuffixProps) {
  return <DateField.Suffix {...props} />;
}

export const DunetaDateField = Object.assign(DunetaDateFieldRoot, {
  Root: DunetaDateFieldRoot,
  Group: DunetaDateFieldGroup,
  Input: DunetaDateFieldInput,
  InputContainer: DunetaDateFieldInputContainer,
  Segment: DunetaDateFieldSegment,
  Prefix: DunetaDateFieldPrefix,
  Suffix: DunetaDateFieldSuffix,
});
