// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { DateField } from '@heroui/react';

export type DunetaDateFieldProps = ComponentProps<typeof DateField>;
export type DunetaDateFieldGroupProps = ComponentProps<typeof DateField.Group>;
export type DunetaDateFieldInputProps = ComponentProps<typeof DateField.Input>;
export type DunetaDateFieldInputContainerProps = ComponentProps<typeof DateField.InputContainer>;
export type DunetaDateFieldSegmentProps = ComponentProps<typeof DateField.Segment>;
export type DunetaDateFieldPrefixProps = ComponentProps<typeof DateField.Prefix>;
export type DunetaDateFieldSuffixProps = ComponentProps<typeof DateField.Suffix>;
