// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ColorSlider } from '@heroui/react';
import type { DunetaColorSliderProps, DunetaColorSliderOutputProps, DunetaColorSliderTrackProps, DunetaColorSliderThumbProps } from './types';

function DunetaColorSliderRoot(props: DunetaColorSliderProps) {
  return <ColorSlider {...props} />;
}

function DunetaColorSliderOutput(props: DunetaColorSliderOutputProps) {
  return <ColorSlider.Output {...props} />;
}

function DunetaColorSliderTrack(props: DunetaColorSliderTrackProps) {
  return <ColorSlider.Track {...props} />;
}

function DunetaColorSliderThumb(props: DunetaColorSliderThumbProps) {
  return <ColorSlider.Thumb {...props} />;
}

export const DunetaColorSlider = Object.assign(DunetaColorSliderRoot, {
  Root: DunetaColorSliderRoot,
  Output: DunetaColorSliderOutput,
  Track: DunetaColorSliderTrack,
  Thumb: DunetaColorSliderThumb,
});
