// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { ColorSlider } from '@heroui/react';

export type DunetaColorSliderProps = ComponentProps<typeof ColorSlider>;
export type DunetaColorSliderOutputProps = ComponentProps<typeof ColorSlider.Output>;
export type DunetaColorSliderTrackProps = ComponentProps<typeof ColorSlider.Track>;
export type DunetaColorSliderThumbProps = ComponentProps<typeof ColorSlider.Thumb>;
