// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Meter } from '@heroui/react';
import type { DunetaMeterProps } from './types';

function DunetaMeterRoot(props: DunetaMeterProps) {
  return <Meter {...props} />;
}

export const DunetaMeter = Object.assign(DunetaMeterRoot, {
  Root: DunetaMeterRoot,
});
