// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Meter } from '@heroui/react';

export type DunetaMeterProps = ComponentProps<typeof Meter>;
