#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const ROUTE_FILES = new Set(['layout.tsx', 'page.tsx', 'entry.server.tsx', 'loading.tsx', 'error.tsx']);
const RESERVED_ROUTE_FILES = new Set([...ROUTE_FILES, 'root.tsx', 'routes.ts']);
const WEB_ROUTES_FILE = path.join('routes', 'web.ts');
const INIT_IMPORT = "import './init-config';\n";

function writeInitConfig(outDir, webConfig) {
  const patch = {
    app: webConfig.app,
    api: webConfig.api,
    theme: webConfig.theme,
    locale: webConfig.locale,
    image: webConfig.image,
  };
  const content = `// AUTO-GENERATED by duneta dev/build — do not edit.
import { bootstrapConfig } from 'duneta/config/client/bootstrap';

bootstrapConfig(${JSON.stringify(patch)});
`;
  fs.writeFileSync(path.join(outDir, 'init-config.ts'), content);
}

/**
 * Merge app/pages (overrides) with starter default routers
 * into .router-runtime/ for React Router.
 */
export function syncRouters(projectRoot, appRoot, dunetaRoot, webConfig) {
  const webPages = path.join(appRoot, 'pages');
  const defaultRouters = path.join(dunetaRoot, 'starter', 'routers');
  const outDir = path.join(appRoot, '.router-runtime');

  if (!fs.existsSync(defaultRouters)) {
    throw new Error(`Missing default routers at ${defaultRouters}`);
  }

  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });
  writeInitConfig(outDir, webConfig);

  const merged = new Map();

  collectRouteFiles(defaultRouters, '', merged, 'client');
  if (fs.existsSync(webPages)) {
    collectRouteFiles(webPages, '', merged, 'web');
  }

  for (const [rel, source] of merged) {
    const src =
      source === 'web' ? path.join(webPages, rel) : path.join(defaultRouters, rel);
    const dest = path.join(outDir, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });

    if (rel.endsWith('layout.tsx')) {
      const theme = webConfig?.theme?.default ?? 'dark';
      const content = fs
        .readFileSync(src, 'utf8')
        .replace(/@duneta\/client\/themes\/globals\.css/g, '~/themes/globals.css')
        .replace(/defaultTheme="[^"]*"/, `defaultTheme="${theme}"`);
      fs.writeFileSync(dest, content);
      continue;
    }

    fs.copyFileSync(src, dest);
  }

  const hasAppRoutes = writeRoutesManifestTs(projectRoot, outDir);

  const layoutFile = path.join(outDir, 'layout.tsx');
  if (!fs.existsSync(layoutFile)) {
    throw new Error('A root layout.tsx is required (starter/routers or app/pages).');
  }

  writeRootTsx(outDir);

  const routesTs = generateRoutesTs(outDir, hasAppRoutes);
  fs.writeFileSync(path.join(outDir, 'routes.ts'), routesTs);

  return outDir;
}

function writeRoutesManifestTs(projectRoot, outDir) {
  const appRoutes = path.join(projectRoot, WEB_ROUTES_FILE);
  const dest = path.join(outDir, 'routes.manifest.ts');

  if (fs.existsSync(appRoutes)) {
    fs.writeFileSync(
      dest,
      `// AUTO-GENERATED by duneta sync — routes/web.ts is the source of truth.
import './init-config';
import { buildWebRouter, type WebRoute } from 'duneta/routes';
import webRoutes from '../../routes/web';

const routes = webRoutes as WebRoute.Config;
export const pageRouter = buildWebRouter(routes.pages ?? []);
`,
    );
    return true;
  }

  fs.writeFileSync(
    dest,
    `// AUTO-GENERATED by duneta sync — add routes/web.ts to register page routes.
import { buildWebRouter } from 'duneta/routes';

export const pageRouter = buildWebRouter([]);
`,
  );
  return false;
}

function writeRootTsx(outDir) {
  const content = `${INIT_IMPORT}export { Layout } from './layout';
export { default } from './layout';
`;
  fs.writeFileSync(path.join(outDir, 'root.tsx'), content);
}

function collectRouteFiles(baseDir, relDir, merged, source) {
  if (!fs.existsSync(baseDir)) return;

  for (const entry of fs.readdirSync(baseDir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;

    const rel = relDir ? path.posix.join(relDir, entry.name) : entry.name;

    if (entry.isDirectory()) {
      collectRouteFiles(path.join(baseDir, entry.name), rel, merged, source);
      continue;
    }

    if (!ROUTE_FILES.has(entry.name) && !entry.name.endsWith('.tsx')) continue;
    if (!entry.name.endsWith('.tsx')) continue;

    merged.set(rel, source);
  }
}

function buildRouteTree(relDir, outDir) {
  const absDir = path.join(outDir, relDir);
  if (!fs.existsSync(absDir)) return [];

  const routes = [];
  const subdirs = fs
    .readdirSync(absDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith('_'))
    .map((entry) => entry.name)
    .sort();

  for (const name of subdirs) {
    const childRel = relDir ? `${relDir}/${name}` : name;
    const childDir = path.join(absDir, name);
    const hasLayout = fs.existsSync(path.join(childDir, 'layout.tsx'));
    const hasPage = fs.existsSync(path.join(childDir, 'page.tsx'));

    if (hasLayout) {
      const children = [];
      if (hasPage) {
        children.push({ type: 'index', file: `${childRel}/page.tsx` });
      }
      children.push(...buildRouteTree(childRel, outDir));
      routes.push({ type: 'layout', file: `${childRel}/layout.tsx`, children });
      continue;
    }

    if (hasPage) {
      const nested = buildRouteTree(childRel, outDir);
      if (nested.length === 0) {
        routes.push({ type: 'route', path: name, file: `${childRel}/page.tsx` });
      } else {
        routes.push({ type: 'route', path: name, file: `${childRel}/page.tsx`, children: nested });
      }
      continue;
    }

    const nested = buildRouteTree(childRel, outDir);
    if (nested.length > 0) {
      routes.push({ type: 'prefix', path: name, children: nested });
    }
  }

  return routes;
}

function emitRouteNodes(nodes, indent) {
  const pad = ' '.repeat(indent);
  const lines = [];

  for (const node of nodes) {
    if (node.type === 'index') {
      lines.push(`${pad}index('${node.file}'),`);
      continue;
    }

    if (node.type === 'route') {
      if (node.children?.length) {
        lines.push(`${pad}route('${node.path}', '${node.file}', [`);
        lines.push(...emitRouteNodes(node.children, indent + 2));
        lines.push(`${pad}]),`);
      } else {
        lines.push(`${pad}route('${node.path}', '${node.file}'),`);
      }
      continue;
    }

    if (node.type === 'layout') {
      lines.push(`${pad}layout('${node.file}', [`);
      lines.push(...emitRouteNodes(node.children, indent + 2));
      lines.push(`${pad}]),`);
      continue;
    }

    if (node.type === 'prefix') {
      lines.push(`${pad}...prefix('${node.path}', [`);
      lines.push(...emitRouteNodes(node.children, indent + 2));
      lines.push(`${pad}]),`);
    }
  }

  return lines;
}

function resourceRoutePath(fileName) {
  return fileName.replace(/\.tsx$/, '').replace(/\[\.\]/g, '.');
}

function collectResourceRoutes(outDir) {
  if (!fs.existsSync(outDir)) return [];

  return fs
    .readdirSync(outDir, { withFileTypes: true })
    .filter(
      (entry) =>
        entry.isFile() &&
        entry.name.endsWith('.tsx') &&
        !RESERVED_ROUTE_FILES.has(entry.name),
    )
    .map((entry) => ({ path: resourceRoutePath(entry.name), file: entry.name }))
    .sort((a, b) => a.path.localeCompare(b.path));
}

function generateRoutesTs(outDir, hasAppRoutes = false) {
  const routes = [];

  for (const resource of collectResourceRoutes(outDir)) {
    routes.push({ type: 'route', path: resource.path, file: resource.file });
  }

  if (!hasAppRoutes) {
    if (fs.existsSync(path.join(outDir, 'page.tsx'))) {
      routes.push({ type: 'index', file: 'page.tsx' });
    }

    routes.push(...buildRouteTree('', outDir));
  }

  const body = emitRouteNodes(routes, 2).join('\n');

  return `import { type RouteConfig, index, layout, prefix, route } from '@react-router/dev/routes';
import { pageRouter } from './routes.manifest';

function toReactPath(path: string) {
  return path.replace(/^\\//, '');
}

function routeNode(routeDef: (typeof pageRouter.routes)[number]) {
  if (typeof routeDef.path !== 'string' || !routeDef.page) return [];

  const path = toReactPath(routeDef.path);
  const page = routeDef.page;
  const pageNode = path === '' ? index(page) : route(path, page);

  if (routeDef.layout && routeDef.layout !== 'layout.tsx') {
    return [layout(routeDef.layout, [pageNode])];
  }

  return [pageNode];
}

export default [
${body}
  ...pageRouter.routes.flatMap(routeNode),
] satisfies RouteConfig;
`;
}

if (import.meta.url === pathToFileURL(path.resolve(process.argv[1] ?? '')).href) {
  const cwd = process.cwd();
  const projectRoot =
    fs.existsSync(path.join(cwd, 'app', 'pages')) || fs.existsSync(path.join(cwd, 'routes', 'web.ts'))
      ? cwd
      : path.dirname(cwd);
  const dunetaRoot =
    process.env.DUNETA_ROOT ??
    [path.resolve(cwd, 'node_modules/duneta')].find(
      (dir) => fs.existsSync(path.join(dir, 'package.json')),
    );

  if (!dunetaRoot) {
    throw new Error('[duneta] duneta package not found. Install duneta.');
  }

  syncRouters(projectRoot, path.join(projectRoot, 'app'), dunetaRoot, { theme: { default: 'dark' } });
}
