// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ToggleButton } from '@heroui/react';
import type { DunetaToggleButtonProps } from './types';

function DunetaToggleButtonRoot(props: DunetaToggleButtonProps) {
  return <ToggleButton {...props} />;
}

export const DunetaToggleButton = Object.assign(DunetaToggleButtonRoot, {
  Root: DunetaToggleButtonRoot,
});
