// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Table } from '@heroui/react';
import type { DunetaTableProps, DunetaTableBodyProps, DunetaTableCellProps, DunetaTableCollectionProps, DunetaTableColumnProps, DunetaTableColumnResizerProps, DunetaTableContentProps, DunetaTableFooterProps, DunetaTableHeaderProps, DunetaTableRowProps, DunetaTableScrollContainerProps, DunetaTableResizableContainerProps } from './types';

function DunetaTableRoot(props: DunetaTableProps) {
  return <Table {...props} />;
}

function DunetaTableBody(props: DunetaTableBodyProps) {
  return <Table.Body {...props} />;
}

function DunetaTableCell(props: DunetaTableCellProps) {
  return <Table.Cell {...props} />;
}

function DunetaTableCollection(props: DunetaTableCollectionProps) {
  return <Table.Collection {...props} />;
}

function DunetaTableColumn(props: DunetaTableColumnProps) {
  return <Table.Column {...props} />;
}

function DunetaTableColumnResizer(props: DunetaTableColumnResizerProps) {
  return <Table.ColumnResizer {...props} />;
}

function DunetaTableContent(props: DunetaTableContentProps) {
  return <Table.Content {...props} />;
}

function DunetaTableFooter(props: DunetaTableFooterProps) {
  return <Table.Footer {...props} />;
}

function DunetaTableHeader(props: DunetaTableHeaderProps) {
  return <Table.Header {...props} />;
}

function DunetaTableRow(props: DunetaTableRowProps) {
  return <Table.Row {...props} />;
}

function DunetaTableScrollContainer(props: DunetaTableScrollContainerProps) {
  return <Table.ScrollContainer {...props} />;
}

function DunetaTableResizableContainer(props: DunetaTableResizableContainerProps) {
  return <Table.ResizableContainer {...props} />;
}

export const DunetaTable = Object.assign(DunetaTableRoot, {
  Root: DunetaTableRoot,
  Body: DunetaTableBody,
  Cell: DunetaTableCell,
  Collection: DunetaTableCollection,
  Column: DunetaTableColumn,
  ColumnResizer: DunetaTableColumnResizer,
  Content: DunetaTableContent,
  Footer: DunetaTableFooter,
  Header: DunetaTableHeader,
  Row: DunetaTableRow,
  ScrollContainer: DunetaTableScrollContainer,
  ResizableContainer: DunetaTableResizableContainer,
});
