// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Table } from '@heroui/react';

export type DunetaTableProps = ComponentProps<typeof Table>;
export type DunetaTableBodyProps = ComponentProps<typeof Table.Body>;
export type DunetaTableCellProps = ComponentProps<typeof Table.Cell>;
export type DunetaTableCollectionProps = ComponentProps<typeof Table.Collection>;
export type DunetaTableColumnProps = ComponentProps<typeof Table.Column>;
export type DunetaTableColumnResizerProps = ComponentProps<typeof Table.ColumnResizer>;
export type DunetaTableContentProps = ComponentProps<typeof Table.Content>;
export type DunetaTableFooterProps = ComponentProps<typeof Table.Footer>;
export type DunetaTableHeaderProps = ComponentProps<typeof Table.Header>;
export type DunetaTableRowProps = ComponentProps<typeof Table.Row>;
export type DunetaTableScrollContainerProps = ComponentProps<typeof Table.ScrollContainer>;
export type DunetaTableResizableContainerProps = ComponentProps<typeof Table.ResizableContainer>;
