// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Autocomplete } from '@heroui/react';
import type { DunetaAutocompleteProps, DunetaAutocompleteTriggerProps, DunetaAutocompleteValueProps, DunetaAutocompleteIndicatorProps, DunetaAutocompletePopoverProps, DunetaAutocompleteFilterProps, DunetaAutocompleteClearButtonProps } from './types';

function DunetaAutocompleteRoot(props: DunetaAutocompleteProps) {
  return <Autocomplete {...props} />;
}

function DunetaAutocompleteTrigger(props: DunetaAutocompleteTriggerProps) {
  return <Autocomplete.Trigger {...props} />;
}

function DunetaAutocompleteValue(props: DunetaAutocompleteValueProps) {
  return <Autocomplete.Value {...props} />;
}

function DunetaAutocompleteIndicator(props: DunetaAutocompleteIndicatorProps) {
  return <Autocomplete.Indicator {...props} />;
}

function DunetaAutocompletePopover(props: DunetaAutocompletePopoverProps) {
  return <Autocomplete.Popover {...props} />;
}

function DunetaAutocompleteFilter(props: DunetaAutocompleteFilterProps) {
  return <Autocomplete.Filter {...props} />;
}

function DunetaAutocompleteClearButton(props: DunetaAutocompleteClearButtonProps) {
  return <Autocomplete.ClearButton {...props} />;
}

export const DunetaAutocomplete = Object.assign(DunetaAutocompleteRoot, {
  Root: DunetaAutocompleteRoot,
  Trigger: DunetaAutocompleteTrigger,
  Value: DunetaAutocompleteValue,
  Indicator: DunetaAutocompleteIndicator,
  Popover: DunetaAutocompletePopover,
  Filter: DunetaAutocompleteFilter,
  ClearButton: DunetaAutocompleteClearButton,
});
