// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Autocomplete } from '@heroui/react';

export type DunetaAutocompleteProps = ComponentProps<typeof Autocomplete>;
export type DunetaAutocompleteTriggerProps = ComponentProps<typeof Autocomplete.Trigger>;
export type DunetaAutocompleteValueProps = ComponentProps<typeof Autocomplete.Value>;
export type DunetaAutocompleteIndicatorProps = ComponentProps<typeof Autocomplete.Indicator>;
export type DunetaAutocompletePopoverProps = ComponentProps<typeof Autocomplete.Popover>;
export type DunetaAutocompleteFilterProps = ComponentProps<typeof Autocomplete.Filter>;
export type DunetaAutocompleteClearButtonProps = ComponentProps<typeof Autocomplete.ClearButton>;
