// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Surface } from '@heroui/react';
import type { DunetaSurfaceProps } from './types';

function DunetaSurfaceRoot(props: DunetaSurfaceProps) {
  return <Surface {...props} />;
}

export const DunetaSurface = Object.assign(DunetaSurfaceRoot, {
  Root: DunetaSurfaceRoot,
});
