// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Surface } from '@heroui/react';

export type DunetaSurfaceProps = ComponentProps<typeof Surface>;
