// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Separator } from '@heroui/react';
import type { DunetaSeparatorProps } from './types';

function DunetaSeparatorRoot(props: DunetaSeparatorProps) {
  return <Separator {...props} />;
}

export const DunetaSeparator = Object.assign(DunetaSeparatorRoot, {
  Root: DunetaSeparatorRoot,
});
