// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ButtonGroup } from '@heroui/react';
import type { DunetaButtonGroupProps, DunetaButtonGroupSeparatorProps } from './types';

function DunetaButtonGroupRoot(props: DunetaButtonGroupProps) {
  return <ButtonGroup {...props} />;
}

function DunetaButtonGroupSeparator(props: DunetaButtonGroupSeparatorProps) {
  return <ButtonGroup.Separator {...props} />;
}

export const DunetaButtonGroup = Object.assign(DunetaButtonGroupRoot, {
  Root: DunetaButtonGroupRoot,
  Separator: DunetaButtonGroupSeparator,
});
