// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { ButtonGroup } from '@heroui/react';

export type DunetaButtonGroupProps = ComponentProps<typeof ButtonGroup>;
export type DunetaButtonGroupSeparatorProps = ComponentProps<typeof ButtonGroup.Separator>;
