// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Menu } from '@heroui/react';
import type { DunetaMenuProps, DunetaMenuItemProps } from './types';

function DunetaMenuRoot(props: DunetaMenuProps) {
  return <Menu {...props} />;
}

function DunetaMenuItem(props: DunetaMenuItemProps) {
  return <Menu.Item {...props} />;
}

export const DunetaMenu = Object.assign(DunetaMenuRoot, {
  Root: DunetaMenuRoot,
  Item: DunetaMenuItem,
});
