// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Menu } from '@heroui/react';

export type DunetaMenuProps = ComponentProps<typeof Menu>;
export type DunetaMenuItemProps = ComponentProps<typeof Menu.Item>;
