// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Accordion } from '@heroui/react';
import type { DunetaAccordionProps, DunetaAccordionItemProps, DunetaAccordionHeadingProps, DunetaAccordionTriggerProps, DunetaAccordionPanelProps, DunetaAccordionIndicatorProps, DunetaAccordionBodyProps } from './types';

function DunetaAccordionRoot(props: DunetaAccordionProps) {
  return <Accordion {...props} />;
}

function DunetaAccordionItem(props: DunetaAccordionItemProps) {
  return <Accordion.Item {...props} />;
}

function DunetaAccordionHeading(props: DunetaAccordionHeadingProps) {
  return <Accordion.Heading {...props} />;
}

function DunetaAccordionTrigger(props: DunetaAccordionTriggerProps) {
  return <Accordion.Trigger {...props} />;
}

function DunetaAccordionPanel(props: DunetaAccordionPanelProps) {
  return <Accordion.Panel {...props} />;
}

function DunetaAccordionIndicator(props: DunetaAccordionIndicatorProps) {
  return <Accordion.Indicator {...props} />;
}

function DunetaAccordionBody(props: DunetaAccordionBodyProps) {
  return <Accordion.Body {...props} />;
}

export const DunetaAccordion = Object.assign(DunetaAccordionRoot, {
  Root: DunetaAccordionRoot,
  Item: DunetaAccordionItem,
  Heading: DunetaAccordionHeading,
  Trigger: DunetaAccordionTrigger,
  Panel: DunetaAccordionPanel,
  Indicator: DunetaAccordionIndicator,
  Body: DunetaAccordionBody,
});
