// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Accordion } from '@heroui/react';

export type DunetaAccordionProps = ComponentProps<typeof Accordion>;
export type DunetaAccordionItemProps = ComponentProps<typeof Accordion.Item>;
export type DunetaAccordionHeadingProps = ComponentProps<typeof Accordion.Heading>;
export type DunetaAccordionTriggerProps = ComponentProps<typeof Accordion.Trigger>;
export type DunetaAccordionPanelProps = ComponentProps<typeof Accordion.Panel>;
export type DunetaAccordionIndicatorProps = ComponentProps<typeof Accordion.Indicator>;
export type DunetaAccordionBodyProps = ComponentProps<typeof Accordion.Body>;
