// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ColorSwatch } from '@heroui/react';
import type { DunetaColorSwatchProps } from './types';

function DunetaColorSwatchRoot(props: DunetaColorSwatchProps) {
  return <ColorSwatch {...props} />;
}

export const DunetaColorSwatch = Object.assign(DunetaColorSwatchRoot, {
  Root: DunetaColorSwatchRoot,
});
