// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { ColorSwatch } from '@heroui/react';

export type DunetaColorSwatchProps = ComponentProps<typeof ColorSwatch>;
