// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Skeleton } from '@heroui/react';
import type { DunetaSkeletonProps } from './types';

function DunetaSkeletonRoot(props: DunetaSkeletonProps) {
  return <Skeleton {...props} />;
}

export const DunetaSkeleton = Object.assign(DunetaSkeletonRoot, {
  Root: DunetaSkeletonRoot,
});
