// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Breadcrumbs } from '@heroui/react';
import type { DunetaBreadcrumbsProps, DunetaBreadcrumbsItemProps } from './types';

function DunetaBreadcrumbsRoot(props: DunetaBreadcrumbsProps) {
  return <Breadcrumbs {...props} />;
}

function DunetaBreadcrumbsItem(props: DunetaBreadcrumbsItemProps) {
  return <Breadcrumbs.Item {...props} />;
}

export const DunetaBreadcrumbs = Object.assign(DunetaBreadcrumbsRoot, {
  Root: DunetaBreadcrumbsRoot,
  Item: DunetaBreadcrumbsItem,
});
