// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Breadcrumbs } from '@heroui/react';

export type DunetaBreadcrumbsProps = ComponentProps<typeof Breadcrumbs>;
export type DunetaBreadcrumbsItemProps = ComponentProps<typeof Breadcrumbs.Item>;
