// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Button } from '@heroui/react';
import type { DunetaButtonProps } from './types';

function DunetaButtonRoot(props: DunetaButtonProps) {
  return <Button {...props} />;
}

export const DunetaButton = Object.assign(DunetaButtonRoot, {
  Root: DunetaButtonRoot,
});
