// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Select } from '@heroui/react';
import type { DunetaSelectProps, DunetaSelectTriggerProps, DunetaSelectValueProps, DunetaSelectIndicatorProps, DunetaSelectPopoverProps } from './types';

function DunetaSelectRoot(props: DunetaSelectProps) {
  return <Select {...props} />;
}

function DunetaSelectTrigger(props: DunetaSelectTriggerProps) {
  return <Select.Trigger {...props} />;
}

function DunetaSelectValue(props: DunetaSelectValueProps) {
  return <Select.Value {...props} />;
}

function DunetaSelectIndicator(props: DunetaSelectIndicatorProps) {
  return <Select.Indicator {...props} />;
}

function DunetaSelectPopover(props: DunetaSelectPopoverProps) {
  return <Select.Popover {...props} />;
}

export const DunetaSelect = Object.assign(DunetaSelectRoot, {
  Root: DunetaSelectRoot,
  Trigger: DunetaSelectTrigger,
  Value: DunetaSelectValue,
  Indicator: DunetaSelectIndicator,
  Popover: DunetaSelectPopover,
});
