// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Select } from '@heroui/react';

export type DunetaSelectProps = ComponentProps<typeof Select>;
export type DunetaSelectTriggerProps = ComponentProps<typeof Select.Trigger>;
export type DunetaSelectValueProps = ComponentProps<typeof Select.Value>;
export type DunetaSelectIndicatorProps = ComponentProps<typeof Select.Indicator>;
export type DunetaSelectPopoverProps = ComponentProps<typeof Select.Popover>;

import type { ReactNode } from 'react';

export type DunetaSelectSingleOption<T extends string = string> = {
  value: T;
  label: ReactNode;
  /** Required for reliable filtering when `label` is not plain text. */
  searchText?: string;
  isDisabled?: boolean;
};

export type DunetaSelectSingleSearchPattern = 'contains' | 'startsWith' | 'exact';

export type DunetaSelectSingleSearchRule = {
  key: 'label' | 'value' | (string & {});
  pattern?: DunetaSelectSingleSearchPattern | RegExp;
};

export type DunetaSelectSingleVirtualConfig = {
  estimatedItemSize?: number;
  maxHeight?: number;
  overscan?: number;
};

export type DunetaSelectSingleSearch =
  | false
  | {
      rules?: readonly DunetaSelectSingleSearchRule[];
      placeholder?: string;
      debounceMs?: number;
    };

export type DunetaSelectSingleProps<T extends string = string> = {
  ariaLabel?: string;
  'aria-label'?: string;
  options: readonly DunetaSelectSingleOption<T>[];
  value?: T | '' | null;
  onChange: (value: T | '') => void;
  placeholder?: string;
  isDisabled?: boolean;
  className?: string;
  fullWidth?: boolean;
  allowClear?: boolean;
  search?: DunetaSelectSingleSearch;
  /** Virtualize large result sets. `true` uses sensible defaults. */
  virtual?: boolean | DunetaSelectSingleVirtualConfig;
};
