// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { InputOTP } from '@heroui/react';
import type { DunetaInputOTPProps, DunetaInputOTPGroupProps, DunetaInputOTPSlotProps, DunetaInputOTPSeparatorProps } from './types';

function DunetaInputOTPRoot(props: DunetaInputOTPProps) {
  return <InputOTP {...props} />;
}

function DunetaInputOTPGroup(props: DunetaInputOTPGroupProps) {
  return <InputOTP.Group {...props} />;
}

function DunetaInputOTPSlot(props: DunetaInputOTPSlotProps) {
  return <InputOTP.Slot {...props} />;
}

function DunetaInputOTPSeparator(props: DunetaInputOTPSeparatorProps) {
  return <InputOTP.Separator {...props} />;
}

export const DunetaInputOTP = Object.assign(DunetaInputOTPRoot, {
  Root: DunetaInputOTPRoot,
  Group: DunetaInputOTPGroup,
  Slot: DunetaInputOTPSlot,
  Separator: DunetaInputOTPSeparator,
});
