// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { InputOTP } from '@heroui/react';

export type DunetaInputOTPProps = ComponentProps<typeof InputOTP>;
export type DunetaInputOTPGroupProps = ComponentProps<typeof InputOTP.Group>;
export type DunetaInputOTPSlotProps = ComponentProps<typeof InputOTP.Slot>;
export type DunetaInputOTPSeparatorProps = ComponentProps<typeof InputOTP.Separator>;
