// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ErrorMessage } from '@heroui/react';
import type { DunetaErrorMessageProps } from './types';

function DunetaErrorMessageRoot(props: DunetaErrorMessageProps) {
  return <ErrorMessage {...props} />;
}

export const DunetaErrorMessage = Object.assign(DunetaErrorMessageRoot, {
  Root: DunetaErrorMessageRoot,
});
