// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { ErrorMessage } from '@heroui/react';

export type DunetaErrorMessageProps = ComponentProps<typeof ErrorMessage>;
