// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { TimeField } from '@heroui/react';
import type { DunetaTimeFieldProps, DunetaTimeFieldGroupProps, DunetaTimeFieldInputProps, DunetaTimeFieldInputContainerProps, DunetaTimeFieldSegmentProps, DunetaTimeFieldPrefixProps, DunetaTimeFieldSuffixProps } from './types';

function DunetaTimeFieldRoot(props: DunetaTimeFieldProps) {
  return <TimeField {...props} />;
}

function DunetaTimeFieldGroup(props: DunetaTimeFieldGroupProps) {
  return <TimeField.Group {...props} />;
}

function DunetaTimeFieldInput(props: DunetaTimeFieldInputProps) {
  return <TimeField.Input {...props} />;
}

function DunetaTimeFieldInputContainer(props: DunetaTimeFieldInputContainerProps) {
  return <TimeField.InputContainer {...props} />;
}

function DunetaTimeFieldSegment(props: DunetaTimeFieldSegmentProps) {
  return <TimeField.Segment {...props} />;
}

function DunetaTimeFieldPrefix(props: DunetaTimeFieldPrefixProps) {
  return <TimeField.Prefix {...props} />;
}

function DunetaTimeFieldSuffix(props: DunetaTimeFieldSuffixProps) {
  return <TimeField.Suffix {...props} />;
}

export const DunetaTimeField = Object.assign(DunetaTimeFieldRoot, {
  Root: DunetaTimeFieldRoot,
  Group: DunetaTimeFieldGroup,
  Input: DunetaTimeFieldInput,
  InputContainer: DunetaTimeFieldInputContainer,
  Segment: DunetaTimeFieldSegment,
  Prefix: DunetaTimeFieldPrefix,
  Suffix: DunetaTimeFieldSuffix,
});
