// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { TimeField } from '@heroui/react';

export type DunetaTimeFieldProps = ComponentProps<typeof TimeField>;
export type DunetaTimeFieldGroupProps = ComponentProps<typeof TimeField.Group>;
export type DunetaTimeFieldInputProps = ComponentProps<typeof TimeField.Input>;
export type DunetaTimeFieldInputContainerProps = ComponentProps<typeof TimeField.InputContainer>;
export type DunetaTimeFieldSegmentProps = ComponentProps<typeof TimeField.Segment>;
export type DunetaTimeFieldPrefixProps = ComponentProps<typeof TimeField.Prefix>;
export type DunetaTimeFieldSuffixProps = ComponentProps<typeof TimeField.Suffix>;
