// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Alert } from '@heroui/react';
import type { DunetaAlertProps, DunetaAlertIndicatorProps, DunetaAlertContentProps, DunetaAlertTitleProps, DunetaAlertDescriptionProps } from './types';

function DunetaAlertRoot(props: DunetaAlertProps) {
  return <Alert {...props} />;
}

function DunetaAlertIndicator(props: DunetaAlertIndicatorProps) {
  return <Alert.Indicator {...props} />;
}

function DunetaAlertContent(props: DunetaAlertContentProps) {
  return <Alert.Content {...props} />;
}

function DunetaAlertTitle(props: DunetaAlertTitleProps) {
  return <Alert.Title {...props} />;
}

function DunetaAlertDescription(props: DunetaAlertDescriptionProps) {
  return <Alert.Description {...props} />;
}

export const DunetaAlert = Object.assign(DunetaAlertRoot, {
  Root: DunetaAlertRoot,
  Indicator: DunetaAlertIndicator,
  Content: DunetaAlertContent,
  Title: DunetaAlertTitle,
  Description: DunetaAlertDescription,
});
