// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Alert } from '@heroui/react';

export type DunetaAlertProps = ComponentProps<typeof Alert>;
export type DunetaAlertIndicatorProps = ComponentProps<typeof Alert.Indicator>;
export type DunetaAlertContentProps = ComponentProps<typeof Alert.Content>;
export type DunetaAlertTitleProps = ComponentProps<typeof Alert.Title>;
export type DunetaAlertDescriptionProps = ComponentProps<typeof Alert.Description>;
