// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Avatar } from '@heroui/react';
import type { DunetaAvatarProps, DunetaAvatarImageProps, DunetaAvatarFallbackProps } from './types';

function DunetaAvatarRoot(props: DunetaAvatarProps) {
  return <Avatar {...props} />;
}

function DunetaAvatarImage(props: DunetaAvatarImageProps) {
  return <Avatar.Image {...props} />;
}

function DunetaAvatarFallback(props: DunetaAvatarFallbackProps) {
  return <Avatar.Fallback {...props} />;
}

export const DunetaAvatar = Object.assign(DunetaAvatarRoot, {
  Root: DunetaAvatarRoot,
  Image: DunetaAvatarImage,
  Fallback: DunetaAvatarFallback,
});
