// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Avatar } from '@heroui/react';

export type DunetaAvatarProps = ComponentProps<typeof Avatar>;
export type DunetaAvatarImageProps = ComponentProps<typeof Avatar.Image>;
export type DunetaAvatarFallbackProps = ComponentProps<typeof Avatar.Fallback>;
