// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Toolbar } from '@heroui/react';
import type { DunetaToolbarProps } from './types';

function DunetaToolbarRoot(props: DunetaToolbarProps) {
  return <Toolbar {...props} />;
}

export const DunetaToolbar = Object.assign(DunetaToolbarRoot, {
  Root: DunetaToolbarRoot,
});
