// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Toolbar } from '@heroui/react';

export type DunetaToolbarProps = ComponentProps<typeof Toolbar>;
