// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { NumberField } from '@heroui/react';
import type { DunetaNumberFieldProps, DunetaNumberFieldGroupProps, DunetaNumberFieldInputProps, DunetaNumberFieldIncrementButtonProps, DunetaNumberFieldDecrementButtonProps } from './types';

function DunetaNumberFieldRoot(props: DunetaNumberFieldProps) {
  return <NumberField {...props} />;
}

function DunetaNumberFieldGroup(props: DunetaNumberFieldGroupProps) {
  return <NumberField.Group {...props} />;
}

function DunetaNumberFieldInput(props: DunetaNumberFieldInputProps) {
  return <NumberField.Input {...props} />;
}

function DunetaNumberFieldIncrementButton(props: DunetaNumberFieldIncrementButtonProps) {
  return <NumberField.IncrementButton {...props} />;
}

function DunetaNumberFieldDecrementButton(props: DunetaNumberFieldDecrementButtonProps) {
  return <NumberField.DecrementButton {...props} />;
}

export const DunetaNumberField = Object.assign(DunetaNumberFieldRoot, {
  Root: DunetaNumberFieldRoot,
  Group: DunetaNumberFieldGroup,
  Input: DunetaNumberFieldInput,
  IncrementButton: DunetaNumberFieldIncrementButton,
  DecrementButton: DunetaNumberFieldDecrementButton,
});
