// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { NumberField } from '@heroui/react';

export type DunetaNumberFieldProps = ComponentProps<typeof NumberField>;
export type DunetaNumberFieldGroupProps = ComponentProps<typeof NumberField.Group>;
export type DunetaNumberFieldInputProps = ComponentProps<typeof NumberField.Input>;
export type DunetaNumberFieldIncrementButtonProps = ComponentProps<typeof NumberField.IncrementButton>;
export type DunetaNumberFieldDecrementButtonProps = ComponentProps<typeof NumberField.DecrementButton>;
