// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Checkbox } from '@heroui/react';
import type { DunetaCheckboxProps } from './types';

function DunetaCheckboxRoot(props: DunetaCheckboxProps) {
  return <Checkbox {...props} />;
}

export const DunetaCheckbox = Object.assign(DunetaCheckboxRoot, {
  Root: DunetaCheckboxRoot,
});
