// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Checkbox } from '@heroui/react';

export type DunetaCheckboxProps = ComponentProps<typeof Checkbox>;
