// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Drawer } from '@heroui/react';
import type { DunetaDrawerProps } from './types';

function DunetaDrawerRoot(props: DunetaDrawerProps) {
  return <Drawer {...props} />;
}

export const DunetaDrawer = Object.assign(DunetaDrawerRoot, {
  Root: DunetaDrawerRoot,
});
