// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Drawer } from '@heroui/react';

export type DunetaDrawerProps = ComponentProps<typeof Drawer>;
