// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { FieldError } from '@heroui/react';
import type { DunetaFieldErrorProps } from './types';

function DunetaFieldErrorRoot(props: DunetaFieldErrorProps) {
  return <FieldError {...props} />;
}

export const DunetaFieldError = Object.assign(DunetaFieldErrorRoot, {
  Root: DunetaFieldErrorRoot,
});
