// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ScrollShadow } from '@heroui/react';
import type { DunetaScrollShadowProps } from './types';

function DunetaScrollShadowRoot(props: DunetaScrollShadowProps) {
  return <ScrollShadow {...props} />;
}

export const DunetaScrollShadow = Object.assign(DunetaScrollShadowRoot, {
  Root: DunetaScrollShadowRoot,
});
