// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { ScrollShadow } from '@heroui/react';

export type DunetaScrollShadowProps = ComponentProps<typeof ScrollShadow>;
