// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ComboBox } from '@heroui/react';
import type { DunetaComboBoxProps, DunetaComboBoxInputGroupProps, DunetaComboBoxTriggerProps, DunetaComboBoxPopoverProps } from './types';

function DunetaComboBoxRoot(props: DunetaComboBoxProps) {
  return <ComboBox {...props} />;
}

function DunetaComboBoxInputGroup(props: DunetaComboBoxInputGroupProps) {
  return <ComboBox.InputGroup {...props} />;
}

function DunetaComboBoxTrigger(props: DunetaComboBoxTriggerProps) {
  return <ComboBox.Trigger {...props} />;
}

function DunetaComboBoxPopover(props: DunetaComboBoxPopoverProps) {
  return <ComboBox.Popover {...props} />;
}

export const DunetaComboBox = Object.assign(DunetaComboBoxRoot, {
  Root: DunetaComboBoxRoot,
  InputGroup: DunetaComboBoxInputGroup,
  Trigger: DunetaComboBoxTrigger,
  Popover: DunetaComboBoxPopover,
});
