// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { ComboBox } from '@heroui/react';

export type DunetaComboBoxProps = ComponentProps<typeof ComboBox>;
export type DunetaComboBoxInputGroupProps = ComponentProps<typeof ComboBox.InputGroup>;
export type DunetaComboBoxTriggerProps = ComponentProps<typeof ComboBox.Trigger>;
export type DunetaComboBoxPopoverProps = ComponentProps<typeof ComboBox.Popover>;
