#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const GENERATED_BANNER = `// AUTO-GENERATED by duneta sync — do not edit.\n`;

export function syncApi(apiRoot) {
  const controllersDir = path.join(apiRoot, 'controllers');
  const repositoriesDir = path.join(apiRoot, 'repositories');
  const routersDir = path.join(apiRoot, 'routers');
  const servicesFile = path.join(apiRoot, 'services.ts');
  const routerFile = path.join(apiRoot, 'router.ts');

  const manualServices = fs.existsSync(servicesFile);
  const manualRouter = fs.existsSync(routerFile);

  const controllerFiles = listFiles(controllersDir, (name) => name.endsWith('-controller.ts'));
  const repositoryFiles = listFiles(repositoriesDir, (name) => name.endsWith('-repository.ts'));
  const routeFiles = listFiles(routersDir, (name) => name.endsWith('.routes.ts'));

  if (!manualServices) {
    fs.writeFileSync(servicesFile, generateServices(controllerFiles, repositoryFiles));
  }

  if (!manualRouter) {
    fs.writeFileSync(routerFile, generateRouter(routeFiles));
  }

  return { manualServices, manualRouter };
}

function listFiles(dir, predicate) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((name) => !name.startsWith('.') && predicate(name))
    .sort();
}

function kebabToPascal(kebab) {
  return kebab
    .split('-')
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

function kebabToCamel(kebab) {
  const pascal = kebabToPascal(kebab);
  return pascal[0].toLowerCase() + pascal.slice(1);
}

function controllerBase(file) {
  return file.slice(0, -'-controller.ts'.length);
}

function repositoryBase(file) {
  return file.slice(0, -'-repository.ts'.length);
}

function controllerClassName(file) {
  return `${kebabToPascal(controllerBase(file))}Controller`;
}

function repositoryClassName(file) {
  return `${kebabToPascal(repositoryBase(file))}Repository`;
}

function routeExportName(file) {
  return `${kebabToCamel(file.slice(0, -'.routes.ts'.length))}Routes`;
}

function generateServices(controllerFiles, repositoryFiles) {
  const repoSet = new Set(repositoryFiles.map(repositoryBase));

  const imports = [
    `import type { RegisterServices } from 'duneta/server/container';`,
    ...repositoryFiles.map(
      (file) => `import { ${repositoryClassName(file)} } from '../repositories/${file.slice(0, -3)}';`,
    ),
    ...controllerFiles.map(
      (file) => `import { ${controllerClassName(file)} } from '../controllers/${file.slice(0, -3)}';`,
    ),
  ];

  const repoLines = repositoryFiles.map((file) => {
    const className = repositoryClassName(file);
    return `  ctx.repositories.singleton('${className}', () => new ${className}());`;
  });

  const controllerLines = controllerFiles.map((file) => {
    const className = controllerClassName(file);
    const base = controllerBase(file);
    if (repoSet.has(base)) {
      const repoClass = repositoryClassName(`${base}-repository.ts`);
      return `  ctx.controllers.singleton('${className}', () => new ${className}(ctx.repositories.resolve('${repoClass}')));`;
    }
    return `  ctx.controllers.singleton('${className}', () => new ${className}());`;
  });

  const body = [
    `export const registerServices: RegisterServices = (ctx) => {`,
    ...repoLines,
    ...(repoLines.length && controllerLines.length ? [''] : []),
    ...controllerLines,
    `};`,
  ];

  return `${GENERATED_BANNER}${imports.join('\n')}\n\n${body.join('\n')}\n`;
}

function generateRouter(routeFiles) {
  const imports = [
    `import type { DunetaServerConfig } from 'duneta/server/configs';`,
    `import type { RequestContext } from 'duneta/server/middlewares';`,
    `import { composeRouter } from 'duneta/server/routers';`,
    `import { Hono } from 'hono';`,
    ...routeFiles.map(
      (file) => `import { ${routeExportName(file)} } from './routers/${file.slice(0, -3)}';`,
    ),
  ];

  const routeNames = routeFiles.map(routeExportName);
  const body =
    routeNames.length === 0
      ? [
          `export function createAppRouter(_config: DunetaServerConfig) {`,
          `  return new Hono<RequestContext>();`,
          `}`,
        ]
      : [
          `export function createAppRouter(_config: DunetaServerConfig) {`,
          `  return composeRouter([${routeNames.join(', ')}]);`,
          `}`,
        ];

  return `${GENERATED_BANNER}${imports.join('\n')}\n\n${body.join('\n')}\n`;
}

if (import.meta.url === pathToFileURL(path.resolve(process.argv[1] ?? '')).href) {
  const result = syncApi(process.cwd());
  if (result.manualServices && result.manualRouter) {
    console.log('[duneta] sync skipped — services.ts and router.ts exist');
  } else {
    console.log('[duneta] synced api/services.ts and api/router.ts');
  }
}
