// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Slider } from '@heroui/react';
import type { DunetaSliderProps, DunetaSliderOutputProps, DunetaSliderTrackProps, DunetaSliderFillProps, DunetaSliderThumbProps, DunetaSliderMarksProps } from './types';

function DunetaSliderRoot(props: DunetaSliderProps) {
  return <Slider {...props} />;
}

function DunetaSliderOutput(props: DunetaSliderOutputProps) {
  return <Slider.Output {...props} />;
}

function DunetaSliderTrack(props: DunetaSliderTrackProps) {
  return <Slider.Track {...props} />;
}

function DunetaSliderFill(props: DunetaSliderFillProps) {
  return <Slider.Fill {...props} />;
}

function DunetaSliderThumb(props: DunetaSliderThumbProps) {
  return <Slider.Thumb {...props} />;
}

function DunetaSliderMarks(props: DunetaSliderMarksProps) {
  return <Slider.Marks {...props} />;
}

export const DunetaSlider = Object.assign(DunetaSliderRoot, {
  Root: DunetaSliderRoot,
  Output: DunetaSliderOutput,
  Track: DunetaSliderTrack,
  Fill: DunetaSliderFill,
  Thumb: DunetaSliderThumb,
  Marks: DunetaSliderMarks,
});
