// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Slider } from '@heroui/react';

export type DunetaSliderProps = ComponentProps<typeof Slider>;
export type DunetaSliderOutputProps = ComponentProps<typeof Slider.Output>;
export type DunetaSliderTrackProps = ComponentProps<typeof Slider.Track>;
export type DunetaSliderFillProps = ComponentProps<typeof Slider.Fill>;
export type DunetaSliderThumbProps = ComponentProps<typeof Slider.Thumb>;
export type DunetaSliderMarksProps = ComponentProps<typeof Slider.Marks>;
