// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ColorArea } from '@heroui/react';
import type { DunetaColorAreaProps, DunetaColorAreaThumbProps } from './types';

function DunetaColorAreaRoot(props: DunetaColorAreaProps) {
  return <ColorArea {...props} />;
}

function DunetaColorAreaThumb(props: DunetaColorAreaThumbProps) {
  return <ColorArea.Thumb {...props} />;
}

export const DunetaColorArea = Object.assign(DunetaColorAreaRoot, {
  Root: DunetaColorAreaRoot,
  Thumb: DunetaColorAreaThumb,
});
