// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { ColorArea } from '@heroui/react';

export type DunetaColorAreaProps = ComponentProps<typeof ColorArea>;
export type DunetaColorAreaThumbProps = ComponentProps<typeof ColorArea.Thumb>;
