// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ToggleButtonGroup } from '@heroui/react';
import type { DunetaToggleButtonGroupProps, DunetaToggleButtonGroupSeparatorProps } from './types';

function DunetaToggleButtonGroupRoot(props: DunetaToggleButtonGroupProps) {
  return <ToggleButtonGroup {...props} />;
}

function DunetaToggleButtonGroupSeparator(props: DunetaToggleButtonGroupSeparatorProps) {
  return <ToggleButtonGroup.Separator {...props} />;
}

export const DunetaToggleButtonGroup = Object.assign(DunetaToggleButtonGroupRoot, {
  Root: DunetaToggleButtonGroupRoot,
  Separator: DunetaToggleButtonGroupSeparator,
});
