// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { ToggleButtonGroup } from '@heroui/react';

export type DunetaToggleButtonGroupProps = ComponentProps<typeof ToggleButtonGroup>;
export type DunetaToggleButtonGroupSeparatorProps = ComponentProps<typeof ToggleButtonGroup.Separator>;
