// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Form } from '@heroui/react';
import type { DunetaFormProps } from './types';

function DunetaFormRoot(props: DunetaFormProps) {
  return <Form {...props} />;
}

export const DunetaForm = Object.assign(DunetaFormRoot, {
  Root: DunetaFormRoot,
});
