// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Form } from '@heroui/react';

export type DunetaFormProps = ComponentProps<typeof Form>;
