// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ListBox } from '@heroui/react';
import type { DunetaListBoxProps, DunetaListBoxItemProps } from './types';

function DunetaListBoxRoot(props: DunetaListBoxProps) {
  return <ListBox {...props} />;
}

function DunetaListBoxItem(props: DunetaListBoxItemProps) {
  return <ListBox.Item {...props} />;
}

export const DunetaListBox = Object.assign(DunetaListBoxRoot, {
  Root: DunetaListBoxRoot,
  Item: DunetaListBoxItem,
});
