// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { ListBox } from '@heroui/react';

export type DunetaListBoxProps = ComponentProps<typeof ListBox>;
export type DunetaListBoxItemProps = ComponentProps<typeof ListBox.Item>;
