// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { DisclosureGroup } from '@heroui/react';
import type { DunetaDisclosureGroupProps } from './types';

function DunetaDisclosureGroupRoot(props: DunetaDisclosureGroupProps) {
  return <DisclosureGroup {...props} />;
}

export const DunetaDisclosureGroup = Object.assign(DunetaDisclosureGroupRoot, {
  Root: DunetaDisclosureGroupRoot,
});
