// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { DisclosureGroup } from '@heroui/react';

export type DunetaDisclosureGroupProps = ComponentProps<typeof DisclosureGroup>;
