// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Input } from '@heroui/react';
import type { DunetaInputProps } from './types';

function DunetaInputRoot(props: DunetaInputProps) {
  return <Input {...props} />;
}

export const DunetaInput = Object.assign(DunetaInputRoot, {
  Root: DunetaInputRoot,
});
