// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.

import type { ComponentProps } from 'react';
import { Input } from '@heroui/react';

export type DunetaInputProps = ComponentProps<typeof Input>;
